language: node_js

node_js:
  - "7"
  - "6"
  - "5"

sudo: false

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm test

after_success:
  - npm run coverage

env:
  - ENV=development LOG_DIR=logs
