language: node_js

node_js:
  - "8"
  - "7"
  - "6"

sudo: false

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - grunt jshint
  - npm test

after_success:
  - npm run coverage

env:
  - ENV=test LOCALE=en
