language: node_js

node_js:
  - "7"
  - "6"
  - "5"

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - npm install -g npm

install:
  - npm install

script:
  - npm run coverage

env:
  - ENV=development LOG_DIR=logs
