language: node_js

node_js:
  - "8"
  - "7"
  - "6"

sudo: true

cache:
  directories:
    - node_modules

before_install:
  - sudo add-apt-repository -y ppa:mc3man/trusty-media
  - sudo apt-get -qq update
  - sudo apt-get install -y ffmpeg

install:
  - npm install

script:
  - grunt jshint
  - npm test

after_success:
  - npm run coverage

env:
  - ENV=test LOCALE=en

addons:
  artifacts:
    s3_region: eu-west-2
    target_paths: $TRAVIS_BUILD_NUMBER
    paths:
      - ./logs
